spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/erd
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  servlet:
    multipart:
      enabled: true
      max-request-size: 10MB
      max-file-size: 10MB
      file-size-threshold: 0
      location: D:/workspaces

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


server:
  error:
    whitelabel:
      enabled: false
    include-stacktrace: never
